apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.24.0  # renovate: datasource=helm depName=loki registryUrl=https://grafana.github.io/helm-charts
    releaseName: loki
    namespace: observability
    valuesFile: values.yaml
    includeCRDs: false
