apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../apps/kube-vip

# Deploy after Cilium but before kube-vip-cloud-provider
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
