apiVersion: v1
kind: Service
metadata:
  name: nut-server
  namespace: monitoring
  labels:
    app: nut-server
spec:
  type: ClusterIP
  ports:
  - port: 3493
    targetPort: 3493
    protocol: TCP
    name: nut
  - port: 9199
    targetPort: 9199
    protocol: TCP
    name: metrics
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: web
  selector:
    app: nut-server
