apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt

resources:
  - ns.yaml
  - pvc.yaml

helmCharts:
  - name: zigbee2mqtt
    repo: https://geek-cookbook.github.io/charts
    version: 9.4.2
    releaseName: zigbee2mqtt
    namespace: zigbee2mqtt
    valuesFile: values.yaml
