apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt

resources:
  - ns.yaml
  - backup-cronjob.yaml
  - sealed-secret.yaml

patches:
  - path: init-container-patch.yaml
    target:
      kind: StatefulSet
      name: zigbee2mqtt

helmCharts:
  - name: zigbee2mqtt
    repo: https://koenkk.github.io/zigbee2mqtt-chart
    version: 2.7.1
    releaseName: zigbee2mqtt
    namespace: zigbee2mqtt
    valuesFile: values.yaml
