apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zigbee2mqtt

resources:
  - ns.yaml
  - backup-cronjob.yaml

helmCharts:
  - name: zigbee2mqtt
    repo: https://koenkk.github.io/zigbee2mqtt-chart
    version: 2.7.1
    releaseName: zigbee2mqtt
    namespace: zigbee2mqtt
    valuesFile: values.yaml
