apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgresql

resources:
  - ns.yaml
  - sealed-secret.yaml
  - authentik-db-rbac.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.1.11
    releaseName: postgresql
    namespace: postgresql
    valuesFile: values.yaml
