installCRDs: true

# Leader election in cert-manager namespace (not kube-system)
global:
  leaderElection:
    namespace: cert-manager

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
  - --leader-election-namespace=cert-manager

webhook:
  securePort: 10260

cainjector:
  enabled: true
  extraArgs:
    - --leader-election-namespace=cert-manager

startupapicheck:
  enabled: true
