apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "2"

resources:
  - ns.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    namespace: longhorn-system
    version: 1.7.2
    valuesFile: values.yaml
    skipHooks: true
