apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - ns.yaml
  - sealed-secret.yaml

helmCharts:
  - name: unpoller
    repo: https://unpoller.github.io/helm-chart
    version: 2.11.2
    releaseName: unifi-poller
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: false
