apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector

resources:
  - ns.yaml

helmCharts:
  - name: vector
    repo: https://helm.vector.dev
    version: 0.38.0  # renovate: datasource=helm depName=vector registryUrl=https://helm.vector.dev
    releaseName: vector
    namespace: vector
    valuesFile: values.yaml
    includeCRDs: false
