apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - sealed-secret.yaml
  - crds

patches:
  - path: prometheus-initcontainer-patch.yaml
    target:
      kind: Prometheus
      name: kube-prometheus-stack-prometheus

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 79.7.1
    releaseName: kube-prometheus-stack
    namespace: observability
    valuesFile: values.yaml
    includeCRDs: false
