apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../apps/kube-vip-cloud-provider
  - configmap.yaml

# Deploy after kube-vip daemonset
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-4"
