apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
    - argocd
    - sealed-secrets
    - kube-vip-cloud-provider
    - cert-manager
    - external-dns
    - longhorn
