apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ../../apps/cilium

# Cilium must be deployed first (before any workloads)
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
