apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-5"

helmCharts:
  - name: kube-vip
    repo: https://kube-vip.github.io/helm-charts
    version: 0.5.0
    releaseName: kube-vip
    namespace: kube-system
    valuesFile: values.yaml
