apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.15.0
    releaseName: external-dns
    namespace: external-dns
    valuesFile: values.yaml

resources:
  - ns.yaml
  - sealed-secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: external-dns-unifi
      namespace: external-dns
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --domain-filter=kng.house