apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - sealed-secret.yaml
  - homeassistant-influxdb-rbac.yaml

helmCharts:
  - name: influxdb2
    repo: https://helm.influxdata.com/
    version: 2.1.2
    releaseName: influxdb
    namespace: observability
    valuesFile: values.yaml
