apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonAnnotations:
  argocd.argoproj.io/sync-wave: "-3"

helmCharts:
  - name: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    version: 2.17.2
    releaseName: sealed-secrets
    namespace: kube-system
    valuesFile: values.yaml
