apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emqx

resources:
  - ns.yaml

helmCharts:
  - name: emqx
    repo: https://repos.emqx.io/charts
    version: 5.8.8
    releaseName: emqx
    namespace: emqx
    valuesFile: values.yaml
