apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  # renovate: datasource=github-releases depName=prometheus-operator/prometheus-operator
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.86.2/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
