---
# Ingress for Code Server through Authentik proxy
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-auth
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    external-dns.alpha.kubernetes.io/hostname: code-home.kng.house
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - code-home.kng.house
      secretName: homeassistant-code-tls
  rules:
    - host: code-home.kng.house
      http:
        paths:
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant-codeserver
                port:
                  number: 12321
