apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-ssh
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant-ssh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: home-assistant-ssh
    spec:
      containers:
        - name: ssh
          image: lscr.io/linuxserver/openssh-server:latest
          ports:
            - name: ssh
              containerPort: 2222
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
            - name: authorized-keys
              mountPath: /authorized-keys
              readOnly: true
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Athens"
            - name: PUBLIC_KEY_FILE
              value: "/authorized-keys/authorized_keys"
            - name: USER_NAME
              value: "hass"
            - name: PASSWORD_ACCESS
              value: "false"
            - name: SUDO_ACCESS
              value: "false"
            - name: DOCKER_MODS
              value: "linuxserver/mods:openssh-server-ssh-tunnel"
          securityContext:
            runAsNonRoot: false
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant
        - name: authorized-keys
          secret:
            secretName: home-assistant-sftp
