---
apiVersion: v1
kind: Service
metadata:
  name: otbr
  namespace: matter-thread
  labels:
    app: otbr
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: rest-api
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: otbr
