apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alloy
resources:
  - ns.yaml
helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 0.12.1
    releaseName: alloy
    namespace: alloy
    valuesFile: values.yaml
