configs:
  params:
    server.insecure: true
  cm:
    create: true
    admin.enabled: true
    kustomize.buildOptions: "--enable-helm"

# GitOps controller - runs on infrastructure nodes
server:
  nodeSelector:
    node.kng/workload-infra: "true"
  ingress:
    enabled: true

controller:
  nodeSelector:
    node.kng/workload-infra: "true"

repoServer:
  nodeSelector:
    node.kng/workload-infra: "true"

applicationSet:
  nodeSelector:
    node.kng/workload-infra: "true"

notifications:
  nodeSelector:
    node.kng/workload-infra: "true"

redis:
  nodeSelector:
    node.kng/workload-infra: "true"

dex:
  nodeSelector:
    node.kng/workload-infra: "true"